name: Deploy to GoDaddy via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Run the deployment on an Ubuntu machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Step to checkout the code from GitHub

      - name: Install FTP client
        run: sudo apt-get install lftp # Install the lftp client for FTP deployment

      - name: Upload files to GoDaddy via FTP
        run: |
          lftp -f "
          set ftp:ssl-allow no  # Disable SSL for FTP
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}:21  # Specify custom port if needed
          mirror -R --exclude-glob .git* --exclude-glob .github* --exclude-glob admin/data/*.sqlite --exclude-glob admin/data/*.db --exclude-glob admin/data/sessions/* --exclude-glob *.log ./ /  # Ensure this path matches your GoDaddy FTP structure
          quit
          "
